version: '3.8'

services:
  db:
    image: postgres
    container_name: dev-postgres-open-board

    ports:
      - 5432:5432

    volumes:
      - ./database/postgres:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=GNX-0093
      - POSTGRES_USER=Testuser
      - POSTGRES_DB=openboard

    restart: always